#!/usr/bin/env bash
set -e

# Install nginx silently
apt-get update -y
apt-get install nginx -y

# Create a custom 404 error page
ERROR_PAGE="/var/www/html/404.html"
echo "Ceci n'est pas une page" > $ERROR_PAGE

# Create nginx config for custom 404
ERROR_CONF="/etc/nginx/conf.d/custom_404.conf"

cat > $ERROR_CONF << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Remove default configs to avoid conflicts
rm -f /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default

# Reload nginx service
service nginx restart
