#!/usr/bin/env bash
# Bash script that configures nginx with custom HTTP response header
# shellcheck disable=SC2154

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a simple HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure nginx with custom header, redirect, and 404 page
# Add custom header, redirect rule, and custom 404 error page to the default server block
sed -i '/listen 80 default_server;/a\\tadd_header X-Served-By $hostname;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart

# Enable nginx to start on boot
update-rc.d nginx enable