#!/usr/bin/env bash
# Install HAProxy and configure load balancing

sudo apt update
sudo apt install -y haproxy

sudo sh -c 'echo "\nlisten myserver
    bind *:80
    balance roundrobin
    server server1 44.202.47.210:80 check
    server server2 3.93.215.54:80 check
" >> /etc/haproxy/haproxy.cfg'

sudo systemctl restart haproxy
sudo systemctl enable haproxy
