#!/usr/bin/env bash
# Install and configure ufw firewall

# Install ufw
apt-get update -y
apt-get install ufw -y

# Reset ufw to default settings
ufw --force reset

# Set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH (port 22)
ufw allow 22/tcp

# Allow HTTP (port 80)
ufw allow 80/tcp

# Allow HTTPS (port 443)
ufw allow 443/tcp

# Enable ufw firewall
ufw --force enable